version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=astrologer_service
      - POSTGRES_USER=nikita
      - POSTGRES_PASSWORD=helloworld111
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DB_SOURCE=postgres://nikita:helloworld111@postgres:5432/astrologer_service?sslmode=disable
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh","postgres:5432", "--", "/app/start.sh"]
    command: ["./main"]